# -*- coding: utf-8 -*-
"""meera raliya

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NNssW5z22OR4aF-McN66gPeev9w6cyYf
"""

import numpy as np

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = {
    'size':[1000,1200,1500,1800,2000,2500,3000,3500,4000,4500],
    'bedrooms':[2,3,4,5,3,1,6,7,8,9],
    'age':[10,8,5,3,1,1,2,3,4,5],
    'price':[10,20,30,40,50,60,70,80,90,100]
}

df=pd.DataFrame(data)

df#whole table

df.head()#shows the first 5

df.tail()#shows the last 5

df.columns#shows the name of coloumn

df.shape#define the nos of row and col

df.info()#define the null and datatype

df.describe()#static value

"""scater plot"""

plt.figure(figsize=(8,2))#to show graph
plt.scatter(df['size'],df['price'])
plt.title("house vs price")
plt.xlabel("size(sq.ft)")
plt.ylabel("price(lakhs)")
plt.grid(True)
plt.show()

"""plot plot"""

plt.figure(figsize=(8,2))#to show point and plot
plt.plot(df['price'],marker='o')
plt.title("house vs price")
plt.xlabel("size(sq.ft)")
plt.ylabel("price(lakhs)")
plt.grid(True)
plt.show()

plt.figure(figsize=(8,2))#to show graph
plt.bar(df.index,df['bedrooms'])
plt.title("bedrooms in each houe")
plt.xlabel("house index")
plt.ylabel("bedrooms")
plt.show()

plt.figure(figsize=(8,2))#to show history
plt.hist(df['age'],bins=18)
plt.title("house vs price")
plt.xlabel("size(sq.ft)")
plt.ylabel("price(lakhs)")
plt.grid(True)
plt.show()

plt.figure(figsize=(8,2))#to show box
plt.boxplot(df['bedrooms'])
plt.title("house vs price")
plt.xlabel("size(sq.ft)")
plt.ylabel("price(lakhs)")
plt.grid(True)
plt.show()